import json
from pathlib import Path


def convert_features(input_path):
    # Read the output generated by apk_features.py.
    data = json.loads(
        Path(input_path).read_text(encoding="utf-8")
    )

    permissions = sorted(set(data["permissions"]))

    record = {
        "schema": "apk-static-v1",
        "sha256": data["sha256"],
        "package": data["package_name"],
        "min_sdk": data["min_sdk"],
        "target_sdk": data["target_sdk"],
        "permissions": permissions,
        "permission_count": len(permissions),
        "suspicious_api_counts": data["suspicious_method_counts"],
    }

    # Sparse-ready feature mapping.
    flat = {
        f"perm::{permission}": 1
        for permission in record["permissions"]
    }

    flat.update({
        f"api::{name}": count
        for name, count in record["suspicious_api_counts"].items()
    })

    return record, flat


if __name__ == "__main__":
    record, flat = convert_features("features.json")

    Path("record.json").write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    Path("flat_features.json").write_text(
        json.dumps(flat, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("Saved: record.json")
    print("Saved: flat_features.json")
    print(json.dumps(flat, indent=2, sort_keys=True))
